Updated max supported version
tinnyx/keepintaskbar pull request #2
Opened 2018-10-31 11:12 UTC by mdjimy

Tested & this extension works just fine even under Thunderbird version 60.2.1

2018-11-07 18:50 UTC, dougbreaux requested changes
Suggest also changing the version to 1.1.

2018-11-13 16:49 UTC, theblackhole commented
@mdjimy Since this project doesn't seem to be active anymore, would you consider making a release with a .xpi on your fork? Or even better, if possible, publishing it?

2019-02-06 18:08 UTC, tinnyx commented
Hi, sorry for ignoring this for so long, but I must've somehow missed this PR. I've already done this same fix yesterday and submitted it for a review, so it shouldn't be long until it's up and running. I'll try my best to not ignore any future PRs.

2019-02-06 18:08 UTC, closed without merging

2019-02-06 18:44 UTC, theblackhole commented
Awesome 😃